pipeline {
    agent any
    stages {
        stage('clone git'){
            steps {
                sh 'mkdir -p repos/jenkins-play'
                dir("repos/jenkins-play") {
                    git branch: "master",
                            credentialsId: "github-token",
                            url: 'https://github.com/JasperJiang/JenkinsPlay'
                }
            }
        }

        stage('build') {
            steps {
                sh('jobdsl2/gradlew -p jobdsl2 clean build jar --debug')
            }
        }

        stage('init'){
            steps {
                sh('find . -path "*/fixture/*" -prune -o -name "ci-repo.yaml" -print > repos.out')
                sh('find . -path "*/fixture/*" -prune -o -name "ci.yaml" -print > components.out')

                sh('cat repos.out')
                sh('cat components.out')
            }
        }

        stage('process'){
            steps {
                jobDsl  targets: ['jobdsl2/src/jobs/jobs.groovy'].join('\n'),
                        additionalClasspath: './jobdsl2/build/libs/jobdsl2.jar',
                        removedJobAction: 'DELETE',
                        removedViewAction: 'DELETE',
                        lookupStrategy: 'SEED_JOB'
            }
        }
    }
}