pipeline {
    agent any
    stages {
        stage('clone git'){
            steps {
                sh 'mkdir -p repos/jenkins-play'
                dir("repos/jenkins-play") {
                    git branch: "master",
                            credentialsId: "github-token",
                            url: 'https://github.com/JasperJiang/JenkinsPlay'
                }
            }
        }

        stage('init'){
            steps {
                sh('find ./repos -name "ci.yaml" > repos.out')
                sh('cat repos.out')
            }
        }

        stage('process'){
            steps {
                jobDsl  targets: ['jobDsl/job.groovy'].join('\n'),
                        removedJobAction: 'DELETE',
                        removedViewAction: 'DELETE',
                        lookupStrategy: 'SEED_JOB'
            }
        }
    }
}